#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
PLUGIN_DIR=$(dirname $0)
APP="$1"
IMAGE="dokku/$APP"
DOCKER_ARGS="-v $DOKKU_ROOT/$APP/ui-cache:/ui-cache"

echo "-----> Building UI (the first time may take awhile)"
id=$(cat "$PLUGIN_DIR/build" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run $DOCKER_ARGS -d $IMAGE /bin/bash -c "/app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Building UI Complete"
