#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"
IMAGE="dokku/$APP"
UICACHE="/ui-cache"
DOCKER_ARGS="-v $DOKKU_ROOT/$APP/ui-cache:/ui-cache"

NODE_VERSION=0.10.28
NODE_URL="http://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
env_path=$DOKKU_ROOT/$APP/ENV
if [[ -f "$env_path" ]]; then
  source $env_path
fi

UISCRIPT="
#!/bin/bash

PATH=$UICACHE/vendor/node/bin:/app/node_modules/.bin:\$PATH
cd /app

if [[ ! -f package.json || ! -f bower.json ]]; then
  exit 0
fi

#install node
if [[ ! -f $UICACHE/vendor/node/bin/node ]]; then
  # Resolve node version using semver.io

  # Download node from Heroku's S3 mirror of nodejs.org/dist
  curl $NODE_URL -s -o - | tar xzf - -C $UICACHE

  # Move node (and npm) into ./vendor and make them executable
  mkdir -p $UICACHE/vendor
  mv $UICACHE/node-v$NODE_VERSION-linux-x64 $UICACHE/vendor/node
  chmod +x $UICACHE/vendor/node/bin/*
fi

#install npm deps
if [[ -f package.json ]]; then
  if [[ -f $UICACHE/node_modules.tar ]]; then
    mv $UICACHE/node_modules.tar .
    tar xf node_modules.tar
    rm node_modules.tar
  fi
  #TODO: bring this back
  #npm prune
  npm install
  if [[ ! -d node_modules/bower ]]; then
    npm install bower
  fi
  if [[ ! -d node_modules/grunt-cli ]]; then
    npm install grunt-cli
  fi
  tar -cf node_modules.tar node_modules
  mv node_modules.tar $UICACHE/
fi

#install bower deps
if [[ -f bower.json ]]; then
  if [[ -f $UICACHE/bower_components.tar ]]; then
    mv $UICACHE/bower_components.tar .
    tar xf bower_components.tar
    rm bower_components.tar
  fi
  bower prune --allow-root --config.interactive=false
  bower install --allow-root --config.interactive=false
  tar -cf bower_components.tar bower_components
  mv bower_components.tar $UICACHE/
fi

if [[ -f Gruntfile.js ]]; then
  if [[ -z \"$BUILDUI\" ]]; then
    grunt
  else
    echo \"Running Custom command: $BUILDUI\"
    $BUILDUI
  fi
fi
"

echo "-----> Building UI (the first time may take awhile)"
id=$(echo "$UISCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run $DOCKER_ARGS -d $IMAGE /bin/bash -c "/app/.buildui")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Building UI Complete"
